
cslConnString: "server=localhost;user id=SA;password=yourStrong(!)Password;database=CSL;connection timeout=30"

clrConnString: "root:1111@tcp(localhost:3306)/clearance?charset=utf8&parseTime=True&loc=UTC"

p2brandConnString: "root:1111@tcp(localhost:3306)/pangpang_brand_sku_location?charset=utf8&parseTime=True&loc=UTC"