
cslConnString: "server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300"
clrConnString: "mslv2_app:Eland^123@tcp(106.14.242.171:3306)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC"
p2brandConnString: "pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_sku_location?charset=utf8&parseTime=True&loc=UTC"

p2brandSkuLocationAPIRoot: "https://qa.p2shop.com.cn/pangpang-brand/sku-location-api/v1"
p2brandColleagueAPIRoot: "https://qa.p2shop.com.cn/pangpang-common/colleague-login-api/api/v1"

autoDistributeDeadlineDays: 30
autoTransferInDeadlineDays: 30

colleagueClearanceUsername: "qa.pangpang"
colleagueClearancePassword: "1111"