
#cslConnString: "server=10.201.10.120;user id=CSL_DEV;password=#fldzm49.7;database=CSL;connection timeout=300"
cslConnString: "server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300"
clrConnString: "mslv2_app:0pL6LA#7@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com:3306)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC"
p2brandConnString: "pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com:3306)/pangpang_brand_sku_location?charset=utf8&parseTime=True&loc=UTC"

p2brandSkuLocationAPIRoot: "https://gateway.p2shop.com.cn/pangpang-brand/sku-location-api/v1"
p2brandColleagueAPIRoot: "https://gateway.p2shop.com.cn/pangpang-common/colleague-login-api/api/v1"

autoDistributeDeadlineDays: 14
autoTransferInDeadlineDays: 14

colleagueClearanceTenantCode: "msl"
colleagueClearanceUsername: "msl"
colleagueClearancePassword: "1111"