
cslConnString: "server=localhost;user id=SA;password=yourStrong(!)Password;database=CSL;connection timeout=30"

invConnString: "root:1111@tcp(localhost:3306)/inventories?charset=utf8&parseTime=True&loc=UTC"

clrConnString: "root:SHUAI2478257#@tcp(localhost:3306)/clearance?charset=utf8&parseTime=True&loc=UTC"

mslConnString: "srx_app:Srx^1234@tcp(infra-staging.srxcloud.com:3306)/srx_brand_sku_location?charset=utf8"