
#cslConnString: "server=10.201.10.120;user id=CSL_DEV;password=#fldzm49.7;database=CSL;connection timeout=300"
cslConnString: "server=10.201.10.120;user id=CSL_APP;password=Wldkdydn09#;database=CSL;connection timeout=300"
clrConnString: "mslv2_app:0pL6LA#7@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com:3306)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC"
p2brandConnString: "pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com:3306)/pangpang_brand_sku_location?charset=utf8&parseTime=True&loc=UTC"

p2brandSkuLocationAPIRoot: "https://gateway.p2shop.com.cn/pangpang-brand/sku-location-api/v1"
p2brandColleagueAPIRoot: "https://gateway.p2shop.com.cn/pangpang-common/colleague-login-api/api/v1"
batchjobAPIRoot: "http://batchjob-api.platform:8000/v1/jobs"

autoDistributeDeadlineDays: 14
autoTransferInDeadlineDays: 14

colleagueClearanceTenantCode: "wplace"
appId: "a85f75eca2a244c79fe18559c56816fb"
appSecretKey: "55353929661a45c6854ef2dbbfc4a807"
serverName: "clearance-adapter"