
cslConnString: "server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300"
clrConnString: "mslv2_app:Eland^123@tcp(139.196.228.246:3307)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC"
p2brandConnString: "pangpang_app:Eland^123@tcp(139.196.228.246:3307)/pangpang_brand_sku_location?charset=utf8&parseTime=True&loc=UTC"

p2brandSkuLocationAPIRoot: "https://staging.p2shop.com.cn/pangpang-brand/sku-location-api/v1"
p2brandColleagueAPIRoot: "https://staging.p2shop.com.cn/pangpang-common/colleague-login-api/api/v1"

autoDistributeDeadlineDays: 30
autoTransferInDeadlineDays: 30

colleagueClearanceTenantCode: "pangpang"
colleagueClearanceUsername: "staging.pangpang"
colleagueClearancePassword: "1111"